#!/usr/bin/env python3
# encoding: utf-8

"""Git commit graph generator."""


import argparse
import sys

# important to read - the graphml won't render nicely by default:
# http://thirld.com/blog/2012/01/31/making-yed-import-labels-from-graphml-files/

import gitgraph.common


def main():

    default_output = 'out.graphml'

    parser = argparse.ArgumentParser(
        description=__doc__)

    parser.add_argument(
        "input",
        help="path to git reposiory, defaults to current.",
        nargs='?',
        default=".")

    parser.add_argument(
        "--output",
        help="path to output graphml, defaults to {}.".format(default_output),
        default="out.graphml")

    parser.add_argument(
        "--range",
        help="commits, e.g.'HEAD~50..'",
        default="")

    args = parser.parse_args()

    commits = gitgraph.common.yield_commits(args.input, args.range)
    graph = gitgraph.common.make_graph(commits)
    gitgraph.common.write_graphml(graph, args.output)
    print("wrote:", args.output)


if __name__ == "__main__":
    sys.exit(main())
